name: ms-gen
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cython
  - matplotlib
  - conda-forge::rdkit
  - conda-forge::python-graphviz
  - conda-forge::pygraphviz
  - pytorch::pytorch=2.4.0
  - pip
  - einops
  - seaborn
  - h5py
